name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Needed if your Hugo site uses git submodules

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Node.js (optional, if you use PostCSS or other Node.js tools)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build the Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo's default output directory
          publish_branch: gh-pages  # The branch where the site will be published

      - name: Clean up gh-pages cache (optional)
        run: git worktree prune
